### ISSUE TITLE
On/Off Zone errors

### ISSUE THREAD

**Issue by DanielZimmer** [Swamp-Ig/izone_custom_component#4]
Hi Swamp-lg,

I have installed your custom component, at the moment all my zone are on/off only but seem to get some funny behavior if the zones are off when I restart HA they appear but I'm not able to turn them on, if they are on when I restart they don't appear at all. I;m also getting the below in the HA logs

2019-03-10 21:57:00 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 231, in async_update_ha_state
    state = self.state
  File "/usr/src/app/homeassistant/components/climate/__init__.py", line 197, in state
    if self.current_operation:
  File "/config/custom_components/izone/climate.py", line 359, in current_operation
    for (key, value) in self._state_to_pizone.items():
AttributeError: 'ZoneDevice' object has no attribute '_state_to_pizone'

Not sure if you can help with this?

**Comment by Swamp-Ig** [comment]
When did you pull the release? I'm part way through pushing up some maintenance changes, and these are dependent on using HA 0.89 since the code changed a bit in this release.

**Comment by andrewsmith01** [comment]
Is there anyway to “sync” the set temperature for all the zones/controller? Like, if one is changed, they all change?

I tried setting up an automation to do this but it didn’t work. 

My use case is I have these listed in HomeKit and it’d be nice to be able to adjust the Set Temperature from any, rather than having to find the “controller”...  ??

**Comment by Swamp-Ig** [comment]
@andrewsmith01 This isn't related to this issue, it's off topic really. Anyhow, you could set this up in node red. Here's a [starting point](https://pastebin.com/NYDmS5c8) to get you going, you'll have to change around some of it but you'll get the general idea.

**Comment by Zac300** [comment]
Hi @Swamp-Ig , I am experiencing the same initial issue that @DanielZimmer identified.
`2019-05-16 16:29:42 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 365, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 248, in _async_write_ha_state
    state = self.state
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py", line 192, in state
    if self.current_operation:
  File "/config/custom_components/izone/climate.py", line 353, in current_operation
    for (key, value) in self._state_to_pizone.items():
AttributeError: 'ZoneDevice' object has no attribute '_state_to_pizone'`

I am running Homeassistant 0.92.2, Please let me know how i can assist with investigations.

**Comment by Zac300** [comment]
@Swamp-Ig disregard my above comment. I pulled down your latest changes (thought i had but and the issue seems to be resolved. Thanks for your component, it's great to be able to add another one of my devices to my home automation.

I'll keep an eye on if the issue re-appears and look forward to further updates

**Comment by Swamp-Ig** [comment]
Glad it's resolved, will close. I thought it had because the line numbers had changed.
